<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { candidateService } from '@/services/candidateService'
import type { JobRecommendationResponse } from '@/types/job'

const router = useRouter()

// ── State ──
const loading = ref(true)
const recommendations = ref<JobRecommendationResponse[]>([])

// ── Load ──
async function loadRecommendations(): Promise<void> {
  loading.value = true
  try {
    const result = await candidateService.getRecommendations(20)
    if (result.data) {
      recommendations.value = result.data
    }
  } finally {
    loading.value = false
  }
}

function goToJob(jobId: string): void {
  router.push(`/jobs/${jobId}`)
}

function scoreColor(score: number): string {
  if (score >= 80) return 'text-success'
  if (score >= 60) return 'text-primary'
  if (score >= 40) return 'text-warning'
  return 'text-gray-500'
}

function scoreBg(score: number): string {
  if (score >= 80) return 'bg-success'
  if (score >= 60) return 'bg-primary'
  if (score >= 40) return 'bg-warning'
  return 'bg-gray-400'
}

onMounted(loadRecommendations)
</script>

<template>
  <div class="max-w-3xl mx-auto px-6 py-8">
    <div class="mb-6">
      <h1 class="text-xl font-bold text-gray-900">Job Recommendations</h1>
      <p class="text-sm text-gray-500 mt-1">AI-matched jobs based on your profile, skills, and preferences.</p>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="space-y-3">
      <div v-for="i in 5" :key="i" class="bg-surface border border-border rounded-lg p-5 shadow-sm animate-pulse">
        <div class="flex items-center gap-4">
          <div class="w-12 h-12 bg-gray-100 rounded-lg shrink-0" />
          <div class="flex-1 space-y-2">
            <div class="h-4 bg-gray-100 rounded w-48" />
            <div class="h-3 bg-gray-100 rounded w-32" />
          </div>
          <div class="h-8 w-16 bg-gray-100 rounded shrink-0" />
        </div>
      </div>
    </div>

    <!-- Empty state -->
    <div v-else-if="recommendations.length === 0" class="bg-surface border border-border rounded-lg p-12 shadow-sm text-center">
      <div class="text-gray-400 text-sm">
        <p class="font-medium mb-1">No recommendations yet</p>
        <p class="text-xs mb-3">Complete your profile and upload your CV to get AI-powered job matches.</p>
        <router-link to="/candidate/candidate-profile" class="text-primary hover:text-primary-hover text-xs font-medium transition">
          Complete Your Profile →
        </router-link>
      </div>
    </div>

    <!-- Results -->
    <div v-else class="space-y-3">
      <div
        v-for="rec in recommendations"
        :key="rec.jobId"
        @click="goToJob(rec.jobId)"
        class="bg-surface border border-border rounded-lg p-5 shadow-sm hover:shadow-md hover:border-primary/30 transition cursor-pointer group"
      >
        <div class="flex items-start gap-4">
          <!-- Match score -->
          <div class="relative w-12 h-12 shrink-0">
            <svg viewBox="0 0 36 36" class="w-full h-full -rotate-90">
              <circle cx="18" cy="18" r="15.5" fill="none" stroke="#e5e7eb" stroke-width="2.5" />
              <circle
                cx="18" cy="18" r="15.5" fill="none" stroke-width="2.5" stroke-linecap="round"
                :class="scoreBg(rec.matchScore).replace('bg-', 'stroke-')"
                :stroke-dasharray="`${(rec.matchScore / 100) * 97.4} 97.4`"
              />
            </svg>
            <span class="absolute inset-0 flex items-center justify-center text-[10px] font-bold" :class="scoreColor(rec.matchScore)">
              {{ rec.matchScore }}%
            </span>
          </div>

          <!-- Job info -->
          <div class="flex-1 min-w-0">
            <h3 class="text-sm font-semibold text-gray-900 group-hover:text-primary transition mb-0.5">
              {{ rec.title }}
            </h3>
            <p class="text-xs text-gray-500 mb-1.5">
              {{ rec.companyName }}
              <span v-if="rec.location" class="text-gray-400"> · {{ rec.location }}</span>
            </p>
            <p class="text-xs text-gray-500 line-clamp-2">{{ rec.matchReason }}</p>
          </div>

          <!-- CTA -->
          <div class="shrink-0 mt-1">
            <span class="text-xs font-medium text-primary opacity-0 group-hover:opacity-100 transition">
              View →
            </span>
          </div>
        </div>
      </div>

      <!-- Footer note -->
      <p class="text-[10px] text-gray-400 text-center mt-4">
        Recommendations are generated by AI based on your profile and CV. Update your profile for better results.
      </p>
    </div>
  </div>
</template>
